# Generated by Django 2.2.7 on 2019-11-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portuguese_content', models.TextField(verbose_name='Texto Português:')),
                ('english_content', models.TextField(verbose_name='Texto Inglês:')),
                ('identifier', models.CharField(max_length=30)),
            ],
        ),
    ]
